### ISSUE TITLE
Broken minHood

### ISSUE THREAD

**Issue by w4bo** [Protelis/Protelis#127]
`minHood(nbr([Infinity, [0, 0]]))` 
returns 
`[Infinity, Infinity]` 
rather than 
`[Infinity, [Infinity, Infinity]]`

**Comment by w4bo** [comment]
`testMinHood3` from `protelis-test` breaks the project build.

As this issue is not going to be closed in the short term, I going to comment this test.

**Comment by DanySK** [comment]
I believe `minHood` (as well as other non `PlusSelf` field reducers) should be defined as
``minHood(defaultValue, fieldToReduce)``

there is currently a sort of runtime type detection in place, but it can't guess defaults at the application level.
Alternatively - but I guess not in Protelis as it is - we could have `whateverHood/1` returning an `Optional` and `whateverHood/2` returning either the computed value of the provided default.

@jakebeal, what's your view of the issue?

**Comment by jakebeal** [comment]
I can see that in general we need to have an option for a default value, and should allow supplying that, since people can have a "min hood" or "max hood" with a custom type.

For the common cases of Numbers and Tuples-used-as-vectors, however, where there is a well-defined order that we can infer, can't we also supply the default ourselves --- even if we aren't using our own value, we have it available as a template.

I would thus envision having a runtime error when somebody supplies something that can't be readily inferred, but doesn't explicitly provide a default value.

**Comment by DanySK** [comment]
Thanks @jakebeal .
I have a working fix for @w4bo 's issue, we can instance tuples recursively. Once it hits the mainline, I will close this and open a discussion thread over default values.

**Comment by DanySK** [comment]
Solved.
