### ISSUE TITLE
Generic typing on Field

### ISSUE THREAD

**Issue by jschewebbn** [Protelis/Protelis#138]
I notice that Field doesn't have the ability for it's sample value to be typed other than as object. Is there a reason for this? Could it be typed in a future version of Protelis?

**Comment by jakebeal** [comment]
I'm not sure why this is, but have a feeling it was considered and rejected for a reason --- @DanySK ?

**Comment by DanySK** [comment]
It was initially generic, but such design choice was of no use, as Protelis is not type checked. On the other hand, it encumbered the interpreter code with unchecked casts - as any field would in the end be a `Field<?>`, as no check was made by the compiler that types were compatible, and Java erasure did the rest. So we had to manually check what was inside the field anyway.

This problem is one of many related to the type system, java interoperability (e.g. exception handling, member access, constructor access), and syntax coherence that Protelis suffers due to its initial design. I am personally convinced that building a type system and injecting all the machinery required to make Protelis an all-round, industry-ready language is more time-costly than rebuilding the whole Protelis as a DSL based upon typed, JVM-based language. I had a prototype in this sense that may deserve to be evaluated, but I hadn't had any chance to work on it recently.

**Comment by jakebeal** [comment]
We hit a case recently where we are passing a Field to a java method that is using it for its map-over-neighbors data contents, and thus the typing would be convenient. But if Protelis can't supply the type, maybe that removes the utility...

**Comment by jschewebbn** [comment]
OK, this makes sense. Doing the type checking in Java is the best we can do then.

**Comment by DanySK** [comment]
Until we get a better Protelis, i think so. Sorry.
