### ISSUE TITLE
Importing static variables from Java

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#139]
Static variables from Java do not seem to be supported at present in Protelis imports.

Consider, for example:

```
import java.lang.Double.MAX_EXPONENT

MAX_EXPONENT
```

Xtext recognizes the import of MAX_EXPONENT as a valid Java EObject, but when MAX_EXPONENT is actually used, we get an error.

**Comment by jakebeal** [comment]
@jschewebbn To your query --- this currently appears to be a bug.

**Comment by DanySK** [comment]
Missing feature maybe, but not a bug. We cannot access fields and constructors. This is one of the tenths of issues we have with Java interoperability (the topic includes typing, exceptions, constructors, generics, etc.), that I believe should be tackled at once with a major rework of Protelis, and possibly inheriting directly from an existing strongly typed JVM language (Kotlin, Scala, Xtend...).

**Comment by DanySK** [comment]
It's just not implemented.

At the time, we decided not to allow field access for Java objects, and the reason was not to violate encapsulation, as fields are commonly private and exposed through methods. Since we have no support for member visibility (another thing that should get solved) it may translate in tons of runtime exceptions due to unaccessible members.
For `public static final` fields, such problem does not apply, and it's really just matter of implementing the thing.

**Comment by jschewebbn** [comment]
In this particular case I'm trying to access an enum value, although I expect it's the same problem.

**Comment by DanySK** [comment]
It is similar. Enums would require yet another code path.

**Comment by jakebeal** [comment]
Bumping this, as we'd like to have this functionality: we are often doing workarounds.

**Comment by DanySK** [comment]
11.1.0 and 11.1.0-j7 have the fix.
