### ISSUE TITLE
Protelis serialized shares are very large

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#166]
When sending Protelis shared state over wireless or wired networks, we've generally used Java serialization. 

Unfortunately, the state shared by Protelis tends to serialize to rather large sizes. For example, recent examination of a ~20kb packet found that its serialization was mostly dominated by just a few dozen Tuples and Doubles.  This is obviously a significant limiter to deployed program complexity, and it seems like it should be possible for these things to be encoded in at least an order of magnitude less space.

**Comment by DanySK** [comment]
In a [recent paper](https://ieeexplore.ieee.org/abstract/document/8644518), I made some measurements and optimizations for trying to run Protelis over very constrained networks. A few notes:

* The current internal structure supporting alignment is not focused on packet size reduction and could be improved.
* The way we stack identifiers should be improved by a clearer mapping of bytecodes (won't improve the size directly, but will likely open new optimization windows).
* We may want to better incapsulate codepath generation, to allow for either simulation/time optimized versions or network/space optimized versions.
* At the network manager level, you can use better serialization systems such as [Kryo](https://github.com/EsotericSoftware/kryo) or [Elsa](https://github.com/jankotek/elsa). Maybe also protocol buffers can be leveraged, but needs to be explored. Those changes I believe should not be made inside Protelis, but on the specific backends.
* Again, at the network manager level, you can use compression to reduce size. LZMA2 

Some usage examples are available [here](https://github.com/DanySK/protelis-lora-mqtt), and in particular [here](https://github.com/DanySK/protelis-lora-mqtt/blob/master/src/test/kotlin/it/unibo/protelis/lora/test/TestProtelisSize.kt) I make some experiments with alternative serializers / compression (note: it's Kotlin code, and at the time I was not yet good in that language as I am now, so I realize it looks a bit clumsy and not as idiomatic as it could).

**Comment by jakebeal** [comment]
In the paper, I see that the best improvements are around 4x; I think it ought to be possible to go a lot smaller than that still, but that's a very good start. You also say: 

> we replaced the default CodePath class of Protelis, optimized for simulations, with a new version, featuring a smaller footprint.

Is this included in the numbers or not? How big of a difference does it make?

**Comment by DanySK** [comment]
Yes it is. The difference with the one used in that work is probably in the order of -20~40% message size. I believe it can me further improved though, if we review and modify the internal machinery of the interpreter. The changes introduced there are rather shallow, because I did not want to fiddle too much with the interpreter internals.

Please note that the paper focuses on very simple examples. The more complex is the application, the larger the generated packet size, the larger is the impact of more efficient serialization and compression (for empty packets, the most efficient encoding is plain JSON, even though it is very inconvenient and worse than the default Java serialization in general).

**Comment by jakebeal** [comment]
Thanks; I've shared this with @jschewebbn. @radarku please note as well.

**Comment by DanySK** [comment]
As a fist pass, if applicable, I would recommend trying Kryo with and without LZMA2 compression in the `NetworkManager` to see if packet size improves and gets to acceptable levels. This may be a simple, quick fix. I would still however review the internals of Protelis to make it easier achieving better results.

Further note: the degree of observability and modifiability we allow for `CodePath`s may have security and privacy impacts. We never looked deeply into these, but it's probably time we at least account for them and try to understand the impact of our design choices.

**Comment by jschewebbn** [comment]
I've added gzip streams to my object streams and gotten about a 10x improvement in network utilization. The other serialization libraries are something I may look at in the future. If Protelis were to add support for other such libraries, that would push me toward a particular implementation.

**Comment by DanySK** [comment]
I believe support "is there", in the sense that AFAIK any object marked as `Serializable` should be serializable by Elsa and Kryo as well.

If this is the case, then I won't make Protelis depend by any serialization implementation, as they do not strictly concern the language. It might make sense to provide a network layer (possibly on top of existing software products such as Akka), but I would view that as a companion project based on Protelis rather than as a part of the project itself.

**Comment by jschewebbn** [comment]
A cursory look at the documentation for Kryo suggests to me that it doesn't just serialize anything that is marked as `Serializable` like Java serialization does. You would need to write serializers for Kryo. I see similar comments in the Elsa documentation.

**Comment by jakebeal** [comment]
Another note that came up in discussion: serialization has a significant processor time cost. Implementing appropriate codecs may help with that as well.

**Comment by DanySK** [comment]
Hi @jschewebbn,
I took a closer look to Kryo. I'm quoting the Kryo README.md:
```java
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import java.io.*;

public class HelloKryo {
   static public void main (String[] args) throws Exception {
      Kryo kryo = new Kryo();
      kryo.register(SomeClass.class);

      SomeClass object = new SomeClass();
      object.value = "Hello Kryo!";

      Output output = new Output(new FileOutputStream("file.bin"));
      kryo.writeObject(output, object);
      output.close();

      Input input = new Input(new FileInputStream("file.bin"));
      SomeClass object2 = kryo.readObject(input, SomeClass.class);
      input.close();   
   }
   static public class SomeClass {
      String value;
   }
}
```
For Kryo, serializers can be specified if a class does not work with the default ones. Among them `SerializingInstantiatorStrategy` supports `Serializable` out of the box.

Am I misunderstanding?

**Comment by jschewebbn** [comment]
That's good to hear. I saw the documentation that said the serializers needed to be registered and assumed that meant they were all custom.

**Comment by DanySK** [comment]
Let me know if you decide to give it a spin, and if you could use my support. In case you can put Kryo in place without any help, I'd be glad to know how effective it is.

**Comment by DanySK** [comment]
@jschewebbn, while searching for a way for improving alignedMap performance, I found [another, possibly better solution than Kryo](https://github.com/RuedigerMoeller/fast-serialization). It's a drop-in replacement for Java serialization which claims to be both faster (and it is faster indeed) and producing smaller packets (on average it does).
I'm likely going for it in the Protelis internals.

**Comment by jschewebbn** [comment]
Thanks for the pointer. I haven't been able to get back to looking at this much. 

One issue related to using serialization is the cache that the default object serialization uses. `ObjectOutput` stream caches the objects that are sent and this causes 2 problems. The first is that memory use grows pretty much without bound and some objects don't get sent because the serializer believes that they have already been sent. I have found that I need to call `reset()` on the stream after each message is sent to combat these issues. I'm not sure if the other solutions have this problem.

**Comment by DanySK** [comment]
More efficient networking is there, and documented as per #219.
@jschewebbn @jakebeal please let me know if there is further work to be done on this issue, otherwise I believe we can close it.

**Comment by jakebeal** [comment]
Agreed: we're good enough for now.

**Comment by jschewebbn** [comment]
An update for those interested. I ran with the fast serialization library and saw a 40% reduction in the amount of data transferred.

**Comment by DanySK** [comment]
Hi @jschewebbn,
can you add some detail? Are you

* using hashing code path? If so, which hashing algorithm?
* compressing the serialized shares before sending? If so, which compression algorithm?

Thanks

**Comment by jschewebbn** [comment]
I tested using Java serialization without compression vs. FST without compression. In both cases I'm using `final CodePathFactory codePathFactory = new HashingCodePathFactory(Hashing.murmur3_128());` to create the code path factory.

In FST I'm using the class `TCPObjectSocket` to do the sharing of objects. I did not need to modify any of the classes that I'm sharing. I only modified my network manager objects.

I had experimented with using gzip compression in the past, but kept getting errors about too many open files.

**Comment by DanySK** [comment]
Thanks for the update!

**Comment by jschewebbn** [comment]
Some additional information. I have since reworked our AP protocol to serialize each AP message individually. This has made it easier to test different serialization techniques and compression algorithms. I did testing where the size of AP messages was compared between FST and Java serialization. In both cases the objects were serialized and then compressed with gzip (standard gzip stream as part of the JDK). With FST the average message size was 8,139 bytes. With Java serialization the average message size was 8,200 bytes.

This suggests that FST doesn't buy us much on reducing network bandwidth.

**Comment by DanySK** [comment]
Thanks for the update.
I guess that the gzip removes most of the duplication than FST would remove from the classic serialization.
I wonder if it's possible to use protocol buffers as serialization format, that should be one of the most efficient things available.

**Comment by jschewebbn** [comment]
Sure, that would be more efficient, but does need modification to the code to create the protocol buffer interface definitions.
