### ISSUE TITLE
Generally improve clarity of errors

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#169]
As reported by @jschewebbn:

> The problems that I've had generally stem from not getting enough
information from errors. Either Protelis failing later than it seems
that could be detected or more commonly the error message being very
obsure for someone not very familiar with Protelis.  I don't have any
current error messages or stack traces to look at though.

**Comment by DanySK** [comment]
It's a hard to tackle without messages and stacktraces, though... please @jschewebbn add details as soon as you run into the issues again!

I believe one issue report per specific issue would be better than tracking all of them here (mostly because it is hard to tell when all the errors are clear enough, I don't really see any point at which we can have certainty of the issue being solved).

**Comment by jakebeal** [comment]
Registered an example as #231 ; others will be added as needed.
