### ISSUE TITLE
null values in Protelis

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#183]
Protelis doesn't support a null value, but Java makes extensive use of it. As a result, we can't easily test for nulls in Protelis and end up either with hard to debug errors or with outsourcing that testing back into Java.  Protelis should thus have a null, if only so we can test for it and case accordingly.

**Comment by DanySK** [comment]
Introducing nulls in Protelis and letting them around aggregate code is probably not a good idea: most languages (not just Kotlin, Scala, Ceylon and other newcomers, but Java as well) are now struggling to deal with null on the JVM in a variety of ways. @mviroli and I extensively discussed the topic, this post is summarizes our discussions.
There are two reasons why Protelis needs null values:
1. Some Java methods return `null`
2. Some Java methods want `null`

Besides interaction with Java, there should be no need of null. This allows Protelis for adopting a null policy which is both fail-fast and clean.

* `null` is not allowed in Protelis, but in very specific places: JVM method calls / JVM field references. If any Protelis evaluation tree node gets evaluated to null, an exception is thrown.
* Null-handling should be performed, as in modern Java/Scala, via an `Optional` or `Option` type.
* When calling a method which returns `null` or `void`, if the value needs to be used (this includes the statement being the last in a block), the call should be wrapped into an `Option`. Of course, if the programmer knows the method call is safe and won't return null (e.g. calls to `Math.sin`), then the `Option` wrap is unnecessary.
* When in need of passing `null` to a Java method, the programmer should use `Option.empty()`. In case the parameter is Optional it would be passed down by the interpreter, otherwise it gets internally translated to null. The only unsupported case, this way, would passing `null` as argument to a Java method that expects an `Optional` parameter, which is something incredibly bad that should never be done anyway (accepting null values for optional parameters is sign of insane API design).

If we go this way, we need to decide how we want to support calls to `Optional`. My proposal would be to add a Java utility to protelis-lang, providing static methods that produce `Optional` and `empty` types. This allows for null-like to be supported with no change to syntax (hence, parser), nor new builtins, but as a simple extension of the existing library. Code should look like:

```java
import org.protelis.lang.Optional.* // Plain Java import
optionOf(maybeNullMethodCallExpectingNull(empty()))
```

Also, we need to chose what to use as preferred Option type.
* Java 8+ `Optional` seems the most natural choice since we are set to abandon Java 7-, however, it's not `Serializable`, so calls like `nbr(optional(maybenull()))` would fail when executed in a network environment relying on Java default serialization (arguably, not a Protelis problem, but still needs to be considered)
* Guava's `Optional` works with older Java and is Serializable
* Streamsupport's `Optional`  is a Java 7 backport of the first item of this list. When we drop Java 7 support, we likely want to drop Streamsupport as well and switch to the JDK's stream implementation, so picking this does not look future-proof
* Custom `Optional` type, backed by any of the former (the Guava one maybe the most reasonable choice due to serializability). The main advantage of this type would be support for monadic use with Protelis lambdas:

```java
optionOf(maybeNullMethodCallExpectingNull(none()))
    .flatMap(self, it -> { optionOf(maybeNull(it)) })
    .map(self, it -> { it.toString() })
    .orElse("my default value")
```

where `self` arguments will be omitted when #29 is fixed.

**Comment by mviroli** [comment]
Actually, as far as I'm concerned, there are few additional notes, to clarify and/or slightly change:
*) null is not allowed syntactically, it can just be produced by a Java method and "immediately" passed to another one.. if it escapes somehow this "channeling", entering the realm of Protelis evaluation, it will raise an exception
*) We (i.e., I) did not agree that "When in need of passing null to a Java method, the programmer should use Option.empty().". Null is null, Option.empty() is Option.empty() and we should not mix them, is not coherent (and leads to the unsupported case you mention above). Rather, when in need of passing null to a Java method you have to rely on a nullFactory written in Java (we could provide one as part of the Java libraries shipped with Protelis), which is coherent with the item above. 
*) On the other hand, I agree that a correct way of receiving a "possibly null" object from a Java method is to pass it to some Java code that digest it, and Optional.ofNullable (or equivalent) makes very sense.

**Comment by DanySK** [comment]
You're right - it's way cleaner and better to have a method that produces null when it's needed. I would still put it in the same library of Option, though. Something like:

```java
package org.protelis.lang;
public class Optionals { // Maybe "NullHandling"?
    public static Object null() { return null; }
    public static Option optionOf(@Nullable Object o) { ... }
    public static Option none() { return optionOf(null); }
}
```

```java
org.protelis.lang.datatype;
public interface Option {
    Object orElse(Object defaultValue);
    Object orFail(String message);
    Object orNull();
    Object map(ExecutionContext context, FunctionDefinition mapper);
    Object flatMap(ExecutionContext context, FunctionDefinition mapper);
    Option filter(ExecutionContext context, FunctionDefinition mapper);
    boolean isPresent();
    boolean isAbsent();
}
```

I purposedly substituted `get()` with `orFail()` and `orNull()`. The implementation can be backed by Guava optionals.

**Comment by jakebeal** [comment]
Let me give some cases to think about, in the form of some code.

Here's a function that needs to convey a value that might be null in as x:
````
package org.foo.bar;
import com.javaprogram.NullNasties.javaMightWantNull;
import com.javaprogram.NullNasties.javaMightGiveNull;

function callAJavaMethod(x) {
  javaMightWantNull(x,3);
  javaMightGiveNull();
}
````

And here's some code that might try to call it:
````
package org.foo.baz;
import org.foo.bar;
import com.javaprogram.NullNasties.javaMightGiveNull;
import com.javaprogram.NullNasties.someOtherFunction;

let y = javaMightGiveNull();
rep(z <- y) {
  if(someOtherFunction(y)) {
    callAJavaMethod(z);
  } else {
    callAJavaMethod(null());
  }
}
````

**Comment by mviroli** [comment]
1) you do not want to handle nulls in Protelis, so you never want to create a function that can possibly take a null. It should rather work with Optionals.. so
javaMightWantNull(x.getOrNull(x),3) // or similar API
2) you do not want your protelis function to return a null, but rather possibly an empty optional, hence:
Optional.ofNullable(javaMightGiveNull()) // or similar API
3) someOtherFunction should return an Optional, and hence you predicate on its emptyness as usual

**Comment by DanySK** [comment]
Is the first Java or Protelis code?

```java
package org.foo.baz;
import org.foo.bar;
import com.javaprogram.NullNasties.javaMightGiveNull;
import com.javaprogram.NullNasties.someOtherFunction;

let y = javaMightGiveNull(); // Fails if the method returns null
rep(z <- y) {
  if(someOtherFunction(y)) {
    callAJavaMethod(z);
  } else {
    callAJavaMethod(null()); // Besides missing import, it's ok
  }
}
```

I'm trying to rewrite it, if I understand the point:
```java
module org.foo.baz;
import org.protelis.lang.Optionals.*;
import com.javaprogram.NullNasties.javaMightGiveNull;
import com.javaprogram.NullNasties.someOtherFunction;

let y = optionalOf(javaMightGiveNull())
rep(z <- y) {
  z.flatMap(it -> {
    optionalOf(callAJavaMethod(if(someOtherFunction(y)) { it } else { null()) } )
  })
}
```

**Comment by jakebeal** [comment]
I think I'm getting the idea from what @mviroli is saying, though not quite sure how the code is intended to actually work (`x.getOrNull(x)`?).

@DanySK The first was intended to be Protelis also. Your rewrite of the second I don't understand, since I don't know what `flatMap` is supposed to be.

**Comment by mviroli** [comment]
Sorry I meant x.getOrNull().. it gets the content of the Optional x, or null if empty..

**Comment by DanySK** [comment]
I'm guessing that `x` is `Option` here. `x.getOrNull(x)` would not be a valid call. `x.getOrNull()` would return `null` if `x` is an empty `Option`, in which case:
* if fed to a Java method as argument, would be passed down to Java
* if fed to a Protelis expression (e.g. `let a = x.getOrNull()`), would cause an early fail.

On `flatMap`, it would work exactly as Java's [`Optional.flatMap`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#flatMap-java.util.function.Function-): invoked on a `Option<X>`, takes a function `(X) -> Option<Y>` as input and returns an `Option<Y>`.
* if called on an empty `Option`, returns an emtpy `Option`
* if called on a present `Option`, returns the result of the function applied to the value stored in the `Option`
[Here](https://www.programcreek.com/java-api-examples/?class=java.util.Optional&method=flatMap) are some code examples from the JDK library.

**Comment by DanySK** [comment]
Let me try to go thorugh the first code example...
```java
module org.foo.bar;
import com.javaprogram.NullNasties.javaMightWantNull;
import com.javaprogram.NullNasties.javaMightGiveNull;
import org.protelis.lang.Optionals.*;

def callAJavaMethod(x) { // here x cannot be null
  javaMightWantNull(x,3); // here no null is passed
  javaMightGiveNull(); // error, as null is returned as result of a Protelis function
}
```

Let me try to write an alternative:
```java
module org.foo.bar;
import com.javaprogram.NullNasties.javaMightWantNull;
import com.javaprogram.NullNasties.javaMightGiveNull;
import org.protelis.lang.Optionals.*;

def callAJavaMethod(x) { // here x is an empty Option
  javaMightWantNull(x.getOrNull(),3); // here null is passed to Java
  optionOf(javaMightGiveNull()); // An Option is returned
}
callAJavaMethod(none()) // passes Option, returns Option
```

I believe that reasoning by code examples could be helpful here

**Comment by jakebeal** [comment]
OK, I think I'm warming to the idea of using Options. 

My intuition here is that:
1. They're effectively typing things as "might be a null" and making us explicitly reason about this fact.
2. They don't significantly increase the complexity of code --- mostly they just require a single additional wrapper/unwrapper at the point where the nulls enter and exit Java.

If this is correct, let's proceed forward with this model.  I'll also confirm with the other BBN folks and see if any of them have unexpected objections.

**Comment by DanySK** [comment]
Dealt with in #222. @jakebeal, if you consider the current implementation satisfactory, can you close the issue?

Thanks

**Comment by jakebeal** [comment]
nulls as options is a reasonable solution, and on that front I think we are OK. This needs to be documented in tutorial material, however.
