### ISSUE TITLE
Please review accidental commit

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#22]
Please review commit: https://github.com/Protelis/Protelis/commit/b8f83d11cb605f2fe2544bf8efe0b7ce395a8f41

This was supposed to be to my personal branch only (now switched to https://github.com/jakebeal/Protelis), but I screwed up my configuration and ended up with it going to both repositories.  Consider this an after-the-fact pull request.

**Comment by DanySK** [comment]
A problem with that commit is that it brings (unwanted, I guess) changes in the Eclipse configuration, e.g. turns off the static code checkers, and uses a Macintosh System JVM instead of a generic JavaSE-1.8 execution environment. Since I see no trace of such changes in the commit message, I suppose those changes were unintentional.
In general, better not commit changes to the IDE configuration along with code changes.

The change in code is totally OK!

Best strategy (cleanest, longest) IMHO is:
1. I force the repository back to f627ce7e3a23f63256826d2e9315ae705dd8064d
2. You reset the last commit on your branch (do **not** use ```--hard``` or you'll lose the files, if unsure make a security copy)
3. You re-commit the code changes, excluding the Eclipse configuration
4. You push them (to both repositories, or you make a pull request, any way is ok)

Alternatively, I can pull your changes, force the old IDE configuration back, and commit+push it. Less tricky, but leaves the repo in a not-optimal state.

Let me know

**Comment by jakebeal** [comment]
You're right, those were not supposed to be committed.
Let's use the alternate path, because I don't trust myself to not screw up the git maneuver here.

**Comment by jakebeal** [comment]
I believe this has been dealt with by pull #25.
