### ISSUE TITLE
Expose CodePath data for custom serialization

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#233]
@jschewebbn is implementing a custom serialization to reduce network traffic, and needs to be able to serialize the CodePath objects, e.g., HashingCodePath. 

Its contents, however, are entirely private, which means it can only be serialized/deserialized via the (bloated) Java serialization interface that we're trying to replace.

Can either the CodePath interface or the HashingCodePath implementation expose other some way to get at its state and reconstruct it, e.g., by transformation to and from a String?

**Comment by jschewebbn** [comment]
The default CodePath type provides all of the information needed to do this transformation. The HashingCodePath type needs to expose the bytes array in some way to allow me to implement this other serialization. I expect that accessing this array requires one making a copy so that the internal structure does not get modified.

**Comment by DanySK** [comment]
PR #234 should solve this

**Comment by jschewebbn** [comment]
Thank you, that will allow custom serializers to be implemented.

**Comment by jakebeal** [comment]
Fixed by #234
