### ISSUE TITLE
Tuple higher-order functions shouldn't require execution context

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#29]
In Tuple, reduce, map, and filter require using "self" as the first argument when called with a Protelis function.  There should be some way for the execution context to be provided implicitly when called from inside of Protelis, since there should generally only be the one Protelis execution context.

**Comment by DanySK** [comment]
I do not think this is a bug. The current setup is done because it goes through a method invocation. A Java method per-se does not know where to find a Protelis context.
A possible solution could be, in MethodCall, to transparently associate the current ExecutionContext to any method that wants it in input. Consider that those Java methods are just quicker shortcuts for their Protelis equivalent (which is recursive and slower).

**Comment by jakebeal** [comment]
I think this is a good approach to take.  Maybe even limit it further as follows:

- If Method M takes n arguments, and the first is an ExecutionContext, then 
  - if M is called with n-1 arguments, insert the ExecutionContext in front
  - if M is called with n arguments, call M with the arguments given.
  - else, it's an error anyway
- all other cases, do not do any special handling

This gives the option both of letting ExecutionContext be implicit and of giving an explicit ExecutionContext if the programmer is doing something tricky / reflective.

**Comment by jakebeal** [comment]
We are generalizing so that we apply to all method calls as follows: if precisely the first argument is an ExecutionContext and if we do not supply one, then implicitly add it.

**Comment by DanySK** [comment]
...then implicitly add it... if you passed the number of expected parameters -1. Otherwise, fail.

**Comment by DanySK** [comment]
This is fixed now. Closing.
