### ISSUE TITLE
Decide how to handle null values

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#63]
Should Protelis support or disapprove of null?
- Opposed: null is awful, and it would be better to not have it
- In favor: lots of Java methods return nulls

So, how do we deal with it?

**Comment by jakebeal** [comment]
I'm going to bump this question again, @DanySK : the more that I'm writing applications, the more often I'm having to tiptoe around Java nulls.

**Comment by DanySK** [comment]
My very opinion is that there are a number of issues of consistency and interoperability (null, exceptions and constructors come to my mind first, but that's the tip of the iceberg). I believe all these issues should be tackled at once by better designing how the language works. I've got an ongoing experiment [here](https://github.com/Spacco/Spacco). It's still very rough and early, so please consider it what it is - a proof of concept.
Basically, it would enable the use of the field calculus primitives by using [Xtend](http://www.eclipse.org/xtend/) or even Java directly (though the second option leads to ugly code, due to Java being not born functional). It produces Java 7 (even Java 6) bytecode as output if properly configured, so no need to backport anything. We would inherit a consistent syntax and all the language features that we must otherwise implement and maintain ourselves (see #96 for instance) from another language.
I would advocate that the effort required to evolve this project to the level where Protelis is now is smaller on the long term than the effort required to implement and maintain all the missing bits and pieces in Protelis - as such, it could be convenient to not tackle these issues on Protelis as-is, but rather to invest in bringing the other infrastructure at the same feature level of Protelis. As I see it, it can be considered a legitimate "Protelis2" candidate.

Since we were historically good at listing pros and cons ;) let me try to list them:

Pros:
* A *type checker*
* Function overloading
* Consistent null management
* Consistent exception management
* Reduced burden of language maintenance: we basically have to check only that our primitives and libraries work. All the language part is offloaded to Xtend.
* Consistent documentation from source (Javadoc)
* Early tests suggest a consistent performance increment (about one order of magnitude, excluding the initialization, that drops to almost zero - though further investigation is required here)
* Full JVM interoperability, bytecode generation, no reflection involved. In principle, this code can be used from Java, Scala, Groovty, Clojure, Kotlin, Jython, JRuby (and so on...) with no intervention - though as @mviroli told me each of those languages, and particularly Scala, would benefit of specific layers over such libraries that make advantage of the specific language features.
* It could act as an intermediate layer for the Scafi DSL, allowing us to write in Scala if we please, and have Scafi running wherever Protelis runs. I hope to unify these systems.

Cons:
* The whole library from @w4bo should get ported
* The whole testing infrastructure should get ported
* In general, the existing Protelis code should get ported, and I don't know how big is your Protelis codebase (my own has been basically integrated in the library, and is reduced to relatively few lines of application code)
* It is *much* less trivial to implement `eval`
* We have less control over the syntax (I'd say no control)
* The operations over fields will become less intutive and require explicit map functions - see [this example](https://github.com/Spacco/Spacco/blob/master/src/main/java/it/unibo/caterva/lib/Spreading.xtend) where I wrote a distanceTo equivalent - please note that for some reason I called `stateful` the rep and `neighbor` the `nbr`. The `[]` syntax indicates lambda expressions (Xtend inherited that from Smalltalk I believe).

**Comment by jakebeal** [comment]
The syntax isn't particularly worrisome to me, nor is the porting --- that sounds like it could be an excellent student project.  

My main concern is about whether the proposed approach can actually _enforce_ alignment.  From what I see in your examples, it looks like context has to be explicitly invoked, and I believe that may lead to composition issues.

**Comment by DanySK** [comment]
Composition issues are dealt with by dependency injection via [Guice](https://github.com/google/guice) - sure developers can screw up by doing things manually, but that's unavoidable in general.

Alignment over an alien language was a concern for me too, and basically the reason why I tried to build a prototype myself before presenting the idea.
I encapsulated the alignment strategy and implemented two. One is relatively slow (any `rep` or `nbr` costs about the same of a Java Exception) but extremely accurate, and inspects the java stacktrace to determine whether or not two points in the code are aligned or not. The second is much quicker, but marks only "relevant" points for alignment - which in turn makes everything non purely functional to align when it should not:
```xtend
val x = 1
ctx.neighbor(x)
```
would align with:
```xtend
ctx.neighbor(2)
```
However, a primitive is provided for explicitly restricting on a key (also used in the implementation of alignedMap, that in this language is no longer a strange builtin object), so ideally every time there is a non purely-functional chunk of code using reps or nbrs it should get wrapped into an `align(someObject, [lambda])` block. This was also necessary to deal with classic `for`-style cycles:
```xtend
for (i: 0 ..< 100) {
   ctx.neighbor(i)
}
```
would in fact break things: there is no way to automatically detect that we are on different points of the computation by stack inspection. The correct form for mixing imperative and field calculus would be:
```xtend
for (i: 0 >.. 100) {
   ctx.restrict(i, [ctx.neighbor(it)])
}
```

In future, or if we find a student willing to work on the idea, we'll deepen and understand if this approach is troublesome or feasible.

**Comment by jakebeal** [comment]
From what I understand, I'm afraid this sounds like a non-starter for the moment. 

The "quick and dirty" approach is definitely no good: it will break unless people explicitly manage their alignment, which loses the whole point of field calculus in the first place.

With the slow-but-accurate approach, I have a hard time imagining that we can actually afford to pay the ~100x (or worse, depending on depth!) slowdown cost of an exception. I do think that experimenting with this would be an excellent student project, though, because it would be great if we could get out of the interpreter business.

**Comment by DanySK** [comment]
Actually, the quick way only breaks if the programmer does something that is not included in field calculus in the first place, namely programming imperatively. The alignment strategy is very similar to the one currently in Protelis, but there is no `All` construct for multi-statement (though it can be provided via library). Also, @metaphori confirmed that the same alignment issue stands in Scafi.

**Comment by jakebeal** [comment]
I believe that we are in agreement. :-) I simply consider this to be a much more serious issue, since imperative programming is so strongly encouraged by Java and Java-like languages. 

In Protelis at present, we have a clear boundary, which a programmer has to take explicit syntactic steps to pass (importing stateful methods).  If we adopt the quick & dirty approach, that boundary will vanish and we will likely have many programs where safe and unsafe blocks are inextricably tangled.

**Comment by DanySK** [comment]
Yes, we are in agreement - but...
```protelis
[0, 1, 2].map(self, (v) -> { nbr(v) })
```
...breaks Protelis alignment already, without any import (due to the method call knowing only the Java stack) ;)

So my feeling is that once we equip Protelis with all the bells and whistles necessary for a deeper integration with Java, we may see more and more of these cases.
Also consider that this alignment issue only applies when `nbr` is used directly: any usage that goes through the library is safe no matter how imperative is the code calling it. This is somehow in line with our attempt at hiding the very mechanisms under the hood.

In any case, to me it would be interesting to deepen the investigation - let's see if we can find resources to do it :)

**Comment by jakebeal** [comment]
Agreed on all fronts.

**Comment by jakebeal** [comment]
Obsoleted by #183
