### ISSUE TITLE
If without else

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#65]
Can we have syntactic sugar for "if" without "else"?
We often want this, but what should the value of the other branch be?  Null?

**Comment by jakebeal** [comment]
Per recent email discussion, it seems the other branch *should* be null.  Resolving this thus depends on the resolution of #63. If we add null, then single-branch if is a simple syntactic sugar:

    if (test) { expr };

is equivalent to

    if (test) { expr } else { null };

**Comment by DanySK** [comment]
We have two choices here, given the discussion in #63 :
* Allowing `if` without only if it's not the last statement (hence, it's a side effect)
* Allowing if without else always, but return an `Option`

I would favor the former, as the second can be introduce later if we realize it's needed without breaking the existing code.

**Comment by jakebeal** [comment]
I don't believe that "only if it's not the last statement" will actually work.  Consider the following:
````
let y = if(foo) { 3 };
y+1;
````
This would be allowed, since the `let` statement isn't the last statement, but it's not just a side effect here.

I think that going with the second option is an elegant solution for all such complex cases.

**Comment by DanySK** [comment]
Let me clarify. Our grammar currently have blocks, statements, and expressions. Blocks contain a sequence of statements. Statements can be expressions, variable declarations, or assignments. Expressions must evaluate to a value (if-else is an expression).

```
b ::= s (; b)?
s ::= e | let | assignment
e ::= if | nbr | rep ...
...
let ::= 'let' v '=' e
```
my proposal is:
```
b ::= s* e  // I need to understand how to deal with semicolons
s ::= e | let | assignment | if-without-else
e ::= if | nbr | rep ...
...
let ::= 'let' v '=' e
```

the if without else would be a valid statement, but not a valid expression. As such, the code you exemplified won't compile.
```
let y = if(foo) { 3 }; // error
y+1;
```
```
if(foo) { 3 }; // works
y+1;
```
```
if(foo) { 3 }; // error
```

**Comment by jakebeal** [comment]
I see.  This feels like a kludge, however, and something that will require extra non-intuitive explanation for a user. Why not just go straight for the Optional-based solution?

**Comment by DanySK** [comment]
Because, without a type checker, that would result in unexpected optionals at runtime. You usually know that an Optional is being manipulated, because you create it as part of an interaction with Java.
Here, we are saying that an `if` expression returns an Optional, unless it also have an else, in which case returns the else branch.

The "if without else is a statement, not an expression" approach is being used throughout all languages I know of where if can be an expression:

python:
```python
>>> a = 2 if 3 > 5
  File "<stdin>", line 1
    a = 2 if 3 > 5
                 ^
SyntaxError: invalid syntax
>>> a = 2 if 3 > 5 else 1
>>> a
1
```

Kotlin, which I'd take as reference for language design choices as it's very likely to be *the* better Java in the future, could be returning `String?` (nullable string type), but chooses to fail clearly instead:
```kotlin
>>> val a = if (3 > 5) 2
error: 'if' must have both main and 'else' branches if used as an expression
val a = if (3 > 5) 2
        ^

>>> val a = if (3 > 5) 2 else 1
>>> a
res2: kotlin.Int = 1
```

scala returns a `Any` (equivalent of Object), while works correctly with a normal if. Explicit types make it fail as expected:
```scala
scala> val a = if (3 > 5) 2
a: AnyVal = ()

scala> val a = if (3 > 5) 2 else 1
a: Int = 1

scala> val a: Int = if (3 > 5) 2
<console>:11: error: type mismatch;
 found   : Unit
 required: Int
       val a: Int = if (3 > 5) 2
```

I would expect any person used to program in any of these languages to be pretty much comfortable with the idea of `if` requiring `else` to be considered an expression returning a value.
Also, please note that the second option is a simple extension, which would not break existing code, while forcing the second would cause backwards compatibility issues if we decide to roll back the change.

**Comment by jakebeal** [comment]
Thank you for the very clear explanation. I also like the clarity of the Kotlin error message. I can see your point and am comfortable to proceed in this manner.
