### ISSUE TITLE
Allow arbitrary expressions in rep initializer

### ISSUE THREAD

**Issue by DanySK** [Protelis/Protelis#73]
`rep` is currently forced to specify a local as initialization value. `let` can be used just before the rep to work this around and still do any kind of badness.
Probably at this point we can just allow arbitrary expressions in the `rep` initializer.

**Comment by jakebeal** [comment]
I concur, with the caveat as we have discussed and is in #74 that they must not be fields: any local return is OK. I have looked at this carefully and I think that allowing arbitrary expressions returning local results lets people to some stupid things but no dangerous things.  

It is a problem for continuous (since you can have a zero-measure area of neighborhood computations between initializers), but unrestricted rep is a problem for continuous anyway, so that's not really a problem.

**Comment by DanySK** [comment]
This is now fixed.
