### ISSUE TITLE
Major releases need to have binaries

### ISSUE THREAD

**Issue by jakebeal** [Protelis/Protelis#89]
Many of our releases are lacking binaries; this should be fixed, since it makes it much harder to incorporate Protelis into systems that need jars rather than using Maven/Gradle.

**Comment by DanySK** [comment]
Hi Jake,
let me document here how to produce a redistributable jar, since there are only few steps:
0. clone the Protelis project, and switch the git repository at the version you'd like to produce a redistributable jar for
0.  make sure you have both Java 8 and Java 7 installed
0. make sure that your JAVA_HOME env variable points to the Java 8 home
0. make sure your JAVA7_HOME env variable points to the Java 7 home (as per instructions for the [Retrolambda Gradle Plugin](https://github.com/evant/gradle-retrolambda)
0. issue ./gradlew fatJar
0. the required artifact will be produced in `build/libs` as `protelis-version-redist.jar`

**Comment by DanySK** [comment]
Protelis 9.0.0 redistributable jar has been attached
